name: Coverity Scan for HBFA-FL Code

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  coverity:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: vapier/coverity-scan-action@2068473c7bdf8c2fb984a6a40ae76ee7facd7a85 # v1.8.0
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        build_language: 'other'
        command: --no-command --fs-capture-search ${{ github.workspace }}/HBFA